services:
  database:
    image: postgres:14-bullseye
    container_name: database
    init: true
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # volumes:
    #   - db:/var/lib/postgresql/
  back:
    depends_on:
      - database
    image: back
    container_name: back
    init: true
    build: back/.
  front:
    depends_on:
      - back
    image: front
    container_name: front
    init: true
    build: front/.
# volumes:
#   db:
#     name: db
#     driver: local